export interface ThemeColors {
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  background: string;
  foreground: string;
  muted: string;
  mutedForeground: string;
  border: string;
  input: string;
  ring: string;
  destructive: string;
  destructiveForeground: string;
  success: string;
  successForeground: string;
  warning: string;
  warningForeground: string;
  info: string;
  infoForeground: string;
}

export interface Theme {
  name: string;
  displayName: string;
  colors: {
    light: ThemeColors;
    dark: ThemeColors;
  };
}

export const themes: Record<string, Theme> = {
  blue: {
    name: 'blue',
    displayName: 'Ocean Blue',
    colors: {
      light: {
        primary: '#2563eb',
        primaryForeground: '#ffffff',
        secondary: '#f1f5f9',
        secondaryForeground: '#0f172a',
        accent: '#f1f5f9',
        accentForeground: '#0f172a',
        background: '#ffffff',
        foreground: '#0f172a',
        muted: '#f8fafc',
        mutedForeground: '#64748b',
        border: '#e2e8f0',
        input: '#e2e8f0',
        ring: '#2563eb',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#3b82f6',
        infoForeground: '#ffffff',
      },
      dark: {
        primary: '#3b82f6',
        primaryForeground: '#ffffff',
        secondary: '#1e293b',
        secondaryForeground: '#f8fafc',
        accent: '#1e293b',
        accentForeground: '#f8fafc',
        background: '#0f172a',
        foreground: '#f8fafc',
        muted: '#1e293b',
        mutedForeground: '#94a3b8',
        border: '#334155',
        input: '#334155',
        ring: '#3b82f6',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#3b82f6',
        infoForeground: '#ffffff',
      },
    },
  },
  purple: {
    name: 'purple',
    displayName: 'Royal Purple',
    colors: {
      light: {
        primary: '#7c3aed',
        primaryForeground: '#ffffff',
        secondary: '#f3f4f6',
        secondaryForeground: '#111827',
        accent: '#f3f4f6',
        accentForeground: '#111827',
        background: '#ffffff',
        foreground: '#111827',
        muted: '#f9fafb',
        mutedForeground: '#6b7280',
        border: '#d1d5db',
        input: '#d1d5db',
        ring: '#7c3aed',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#8b5cf6',
        infoForeground: '#ffffff',
      },
      dark: {
        primary: '#8b5cf6',
        primaryForeground: '#ffffff',
        secondary: '#374151',
        secondaryForeground: '#f9fafb',
        accent: '#374151',
        accentForeground: '#f9fafb',
        background: '#111827',
        foreground: '#f9fafb',
        muted: '#374151',
        mutedForeground: '#9ca3af',
        border: '#4b5563',
        input: '#4b5563',
        ring: '#8b5cf6',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#8b5cf6',
        infoForeground: '#ffffff',
      },
    },
  },
  green: {
    name: 'green',
    displayName: 'Forest Green',
    colors: {
      light: {
        primary: '#059669',
        primaryForeground: '#ffffff',
        secondary: '#f0fdf4',
        secondaryForeground: '#14532d',
        accent: '#f0fdf4',
        accentForeground: '#14532d',
        background: '#ffffff',
        foreground: '#14532d',
        muted: '#f7fee7',
        mutedForeground: '#65a30d',
        border: '#d1fae5',
        input: '#d1fae5',
        ring: '#059669',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#06b6d4',
        infoForeground: '#ffffff',
      },
      dark: {
        primary: '#10b981',
        primaryForeground: '#ffffff',
        secondary: '#1f2937',
        secondaryForeground: '#f0fdf4',
        accent: '#1f2937',
        accentForeground: '#f0fdf4',
        background: '#0f1419',
        foreground: '#f0fdf4',
        muted: '#1f2937',
        mutedForeground: '#84cc16',
        border: '#374151',
        input: '#374151',
        ring: '#10b981',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#06b6d4',
        infoForeground: '#ffffff',
      },
    },
  },
  orange: {
    name: 'orange',
    displayName: 'Sunset Orange',
    colors: {
      light: {
        primary: '#ea580c',
        primaryForeground: '#ffffff',
        secondary: '#fff7ed',
        secondaryForeground: '#9a3412',
        accent: '#fff7ed',
        accentForeground: '#9a3412',
        background: '#ffffff',
        foreground: '#9a3412',
        muted: '#fef3c7',
        mutedForeground: '#d97706',
        border: '#fed7aa',
        input: '#fed7aa',
        ring: '#ea580c',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#f97316',
        infoForeground: '#ffffff',
      },
      dark: {
        primary: '#f97316',
        primaryForeground: '#ffffff',
        secondary: '#292524',
        secondaryForeground: '#fff7ed',
        accent: '#292524',
        accentForeground: '#fff7ed',
        background: '#1c1917',
        foreground: '#fff7ed',
        muted: '#292524',
        mutedForeground: '#fb923c',
        border: '#44403c',
        input: '#44403c',
        ring: '#f97316',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#f97316',
        infoForeground: '#ffffff',
      },
    },
  },
  pink: {
    name: 'pink',
    displayName: 'Cherry Blossom',
    colors: {
      light: {
        primary: '#db2777',
        primaryForeground: '#ffffff',
        secondary: '#fdf2f8',
        secondaryForeground: '#831843',
        accent: '#fdf2f8',
        accentForeground: '#831843',
        background: '#ffffff',
        foreground: '#831843',
        muted: '#fce7f3',
        mutedForeground: '#be185d',
        border: '#f9a8d4',
        input: '#f9a8d4',
        ring: '#db2777',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#ec4899',
        infoForeground: '#ffffff',
      },
      dark: {
        primary: '#ec4899',
        primaryForeground: '#ffffff',
        secondary: '#2d1b69',
        secondaryForeground: '#fdf2f8',
        accent: '#2d1b69',
        accentForeground: '#fdf2f8',
        background: '#1e1b4b',
        foreground: '#fdf2f8',
        muted: '#2d1b69',
        mutedForeground: '#f472b6',
        border: '#4c1d95',
        input: '#4c1d95',
        ring: '#ec4899',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#ec4899',
        infoForeground: '#ffffff',
      },
    },
  },
  cream: {
    name: 'cream',
    displayName: 'Warm Cream',
    colors: {
      light: {
        primary: '#dc2626',
        primaryForeground: '#ffffff',
        secondary: '#fefcf3',
        secondaryForeground: '#78716c',
        accent: '#fefcf3',
        accentForeground: '#78716c',
        background:
          'linear-gradient(180deg, #fefcf3 0%, #fef9f3 20%, #fef5f0 40%, #fef2ed 60%, #fed7c3 80%, #fdba8c 100%)',
        foreground: '#78716c',
        muted: '#f5f5f4',
        mutedForeground: '#a8a29e',
        border: '#e7e5e4',
        input: '#e7e5e4',
        ring: '#dc2626',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#dc2626',
        infoForeground: '#ffffff',
      },
      dark: {
        primary: '#f87171',
        primaryForeground: '#ffffff',
        secondary: '#292524',
        secondaryForeground: '#fefcf3',
        accent: '#292524',
        accentForeground: '#fefcf3',
        background:
          'linear-gradient(180deg, #1c1917 0%, #292524 20%, #44403c 40%, #57534e 60%, #78716c 80%, #a8a29e 100%)',
        foreground: '#fefcf3',
        muted: '#292524',
        mutedForeground: '#a8a29e',
        border: '#44403c',
        input: '#44403c',
        ring: '#f87171',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        successForeground: '#ffffff',
        warning: '#f59e0b',
        warningForeground: '#ffffff',
        info: '#f87171',
        infoForeground: '#ffffff',
      },
    },
  },
};

export const defaultTheme = 'cream';
